language: node_js
node_js:
  - stable
  - lts/*
  - 6.9
env:
  - WEBPACK_CORE=4
  - WEBPACK_CORE=5
jobs:
  exclude:
  - node_js: 6.9
    env: WEBPACK_CORE=5
before_install:
  - stty columns 120
install:
  - travis_retry npm install --ignore-scripts --force --legacy-peer-deps
  - travis_retry npm install "webpack@$WEBPACK_CORE" --ignore-scripts --force --legacy-peer-deps
script:
  - travis_retry npm test
